openapi: "3.0.0"
info:
  title: "ストリートライトAPI"
  version: "1.0.0"
  description: "このAPIは街灯をリモートで管理するためのものです。"
  license:
    name: "Apache 2.0"
    url: "https://www.apache.org/licenses/LICENSE-2.0"
servers:
  - url: "test.mykafkacluster.org:18092"
    description: "テストサーバー"
defaultContentType: "application/json"
channels:
  街灯.1.0.イベント.{街灯ID}.照明.測定:
    description: "照明の測定値を送受信するトピック。"
    parameters:
      街灯ID:
        description: "街灯のID。"
        schema:
          type: "string"
    publish:
      summary: "特定の街灯の照明状況を通知する。"
      operationId: "receiveLightMeasurement"
      message:
        name: "lightMeasured"
        title: "照明測定"
        summary: "特定の街灯の照明状況を通知する。"
        contentType: "application/json"
        payload:
          type: "object"
          properties:
            ルーメン:
              type: "integer"
              minimum: 0
              description: "測定された光の強さ（ルーメン）。"
            送信時刻:
              type: "string"
              format: "date-time"
              description: "メッセージが送信された日時。"
  街灯.1.0.アクション.{街灯ID}.オン:
    parameters:
      街灯ID:
        description: "街灯のID。"
        schema:
          type: "string"
    subscribe:
      operationId: "turnOn"
      message:
        name: "turnOnOff"
        title: "オン/オフ"
        summary: "特定の街灯をオンまたはオフにするコマンド。"
        payload:
          type: "object"
          properties:
            コマンド:
              type: "string"
              enum:
                - "on"
                - "off"
              description: "ライトをオンまたはオフにする。"
            送信時刻:
              type: "string"
              format: "date-time"
              description: "メッセージが送信された日時。"
components:
  messages:
    lightMeasured:
      name: "lightMeasured"
      title: "照明測定"
      summary: "特定の街灯の照明状況を通知する。"
      contentType: "application/json"
      payload:
        type: "object"
        properties:
          ルーメン:
            type: "integer"
            minimum: 0
            description: "測定された光の強さ（ルーメン）。"
          送信時刻:
            type: "string"
            format: "date-time"
            description: "メッセージが送信された日時。"
    turnOnOff:
      name: "turnOnOff"
      title: "オン/オフ"
      summary: "特定の街灯をオンまたはオフにするコマンド。"
      payload:
        type: "object"
        properties:
          コマンド:
            type: "string"
            enum:
              - "on"
              - "off"
            description: "ライトをオンまたはオフにする。"
          送信時刻:
            type: "string"
            format: "date-time"
            description: "メッセージが送信された日時。"
  schemas:
    lightMeasuredPayload:
      type: "object"
      properties:
        ルーメン:
          type: "integer"
          minimum: 0
          description: "測定された光の強さ（ルーメン）。"
        送信時刻:
          type: "string"
          format: "date-time"
          description: "メッセージが送信された日時。"
    turnOnOffPayload:
      type: "object"
      properties:
        コマンド:
          type: "string"
          enum:
            - "on"
            - "off"
          description: "ライトをオンまたはオフにする。"
        送信時刻:
          type: "string"
          format: "date-time"
          description: "メッセージが送信された日時。"
  parameters:
    街灯ID:
      description: "街灯のID。"
      schema:
        type: "string"